stages:
  - build
  - test
  - deploy

build_job:
  image: python:latest 
  stage: build
  script:
    - echo "Builds up the virtual environment..."
    - python3 -V
    - pip3 install -r requirements.txt

test_job:
  stage: test
  script:
    - echo "Tests the test files..."
    - python3 test.py:w

deploy_job:
  image: ruby:latest
  stage: deploy
  script:
    - echo "Deploys on heroku..."
    - dpl --provider=heroku --app=allergenius --api-key=$HEROKU_API_KEY