stages:
  - build
  - test
  - deploy

build_job:
  image: python:latest 
  stage: build
  script:
    - echo "Builds up the virtual environment..."
    - python3 -V
    - pip3 install -r requirements.txt

test_job:
  stage: test
  script:
    - echo "Tests the test files..."
    - python3 test.py

deploy_vm_job:
  stage: deploy
  variables:
    PORT: 5000
  before_script:
    - fuser -n tcp -k $PORT || true
  script:
    - echo "Deploys on vm..."
    #- python3 -m flask run

deploy_heroku_job:
  image: ruby:latest
  stage: deploy
  script:
    - echo "Deploys on heroku..."
    - gem install dpl --user-install
    - dpl --provider=heroku --app=allergenius --api-key=$HEROKU_API_KEY