stages:
  - test

test_app:
  image: python:latest
  stage: test
  before_script:
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  script:
    - pip install Flask
    - python test.py