allergenius:
 script:
 - apt-get update -qy
 - apt-get install -y python-dev python-pip
 - pip install -r requirements.txt
 - export MONGOHQ_URL=$MONGO_URL
 
production:
 type: deploy
 script:
 - apt-get update -qy
 - dpl --provider=heroku --app=allergenius --api-key=$HEROKU_API_KEY
 only:
 - master