stages:
  - build
  - test
  - deploy

build_job:
  image: python:latest 
  stage: build
  script:
    - echo "Builds up the virtual environment..."
    - python3 -V
    - pip3 install -r requirements.txt

test_job:
  stage: test
  script:
    - echo "Tests the test files..."
    - python3 test.py

deploy_job:
  stage: deploy
  script:
    - echo "Deploys on heroku..."
    - dpl --provider=heroku --app=<login>-simplewebapp --api-key=$HEROKU_API_KEY