stages:
  - test

test_app:
  image: python:latest
  stage: test
  before_script:
    - sudo apt-get update -qy
    - sudo apt-get install -y python-dev python-pip
    - sudo pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - sudo pip install -r requirements.txt
  script:
    - sudo pip install Flask
    - python test.py