stages:
  - build
  - test

build_job:
  stage: build
  script:
    - echo "Builds up the virtual environment:"
    - export PYTHONPATH=.
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt

test_job:
  stage: test
  script:
    - echo "Tests the test files"
    - python3 test.py