stages:
  - test

test_app:
  image: python:latest
  stage: test
  before_script:
    - python3 -V
    - sudo pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - sudo pip install -r requirements.txt
  script:
    - sudo pip install Flask
    - python test.py